### ISSUE TITLE
PUBAPI-1479 changes plugin architecture

### ISSUE THREAD

**Issue by bahamat** [bahamat/cloudapi-plugins#1]
* [PUBAPI-1476](https://smartos.org/bugview/PUBAPI-1476)
* [TRITON-312](https://smartos.org/bugview/TRITON-312)

**Comment by marsell** [comment]
You'll want to change this line: https://github.com/bahamat/cloudapi-plugins/blob/master/allow_ip_spoofing.js#L85

To:

var ipv4Uuid = network.ipv4_uuid || network.uuid;

Unfortunately, this is one internal docker detail that escaped until too late for this release.

**Comment by bahamat** [comment]
Fixed in 334fdde, along with the sdc-docker bug.
